services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    ports:
      - "5244:5244"
    volumes:
      - ./alist_data:/opt/alist/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
